
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const aspectRatios: { [key: number]: "1:1" | "4:3" | "3:4" | "16:9" | "9:16" } = {
  1: "1:1",
  1.333: "4:3",
  0.75: "3:4",
  1.777: "16:9",
  0.5625: "9:16"
}

function getClosestAspectRatio(ratio: number): "1:1" | "4:3" | "3:4" | "16:9" | "9:16" {
    const supportedRatios = Object.keys(aspectRatios).map(Number);
    const closest = supportedRatios.reduce((prev, curr) => 
        (Math.abs(curr - ratio) < Math.abs(prev - ratio) ? curr : prev)
    );
    return aspectRatios[closest];
}


export async function generateImage(prompt: string, ratio: number): Promise<string> {
    const enhancedPrompt = `A beautiful, high-resolution, vibrant, photorealistic image of: ${prompt}`;
    const aspectRatio = getClosestAspectRatio(ratio);
    
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001', 
            prompt: enhancedPrompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/png',
              aspectRatio: aspectRatio,
            },
        });
        
        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes = response.generatedImages[0].image.imageBytes;
            return base64ImageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate image. Please check your prompt or API key.");
    }
}
